version: "3.11"
services:
  django_blog:
    build:
      context: .
    container_name: django_blog
    command: [ "/django_blog/docker/app.sh" ]
    ports:
      - 8000:8000
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15.4
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
