# Generated by Django 4.2.3 on 2023-07-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='short_description',
            new_name='description',
        ),
    ]
